#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''
[ Script ]

geoipfetch

PT-br:
Geo Localizacao com base no IP fornecido
----------------------------
EN:
Geo Localization from a Given IP Address

rlima@gmail.com
$Id: geoipfetch, v 1 2017/06/28 rlima Exp rlima $

[ License ]

Copyright (c) 2017 Reinaldo Marques de Lima reimlima@gmail.com                                            

PT-br:
A  permissão  é  concedida, a título gratuito, a qualquer pessoa que obtenha uma   cópia deste software e 
arquivos de  documentação  associados (o "Software"), para lidar com o Software sem restrição, incluindo, 
sem limitação,  os  direitos  de  usar,  copiar,  modificar, mesclar, publicar, distribuir, sublicenciar, 
e / ou vender cópias do Software, e  permitir  que as  pessoas a  quem  o  Software  é fornecido o façam, 
sujeito às seguintes condições:

O  aviso  de  copyright  acima e este aviso de permissão devem ser incluídos em todas as cópias ou partes 
substanciais do Software.

O  SOFTWARE  É  FORNECIDO  "COMO ESTÁ", SEM GARANTIA  DE QUALQUER TIPO, EXPRESSA OU IMPLÍCITA, INCLUINDO, 
SEM LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UM DETERMINADO FIM E NÃO VIOLAÇÃO. EM  NENHUM 
CASO  OS  AUTORES  OU  DIREITOS  AUTORAIS TITULARES  SERÃO RESPONSÁVEIS POR QUALQUER RECLAMAÇÃO, DANOS OU 
OUTRAS RESPONSABILIDADES, SEJA EM UMA  AÇÃO DE CUMPRIMENTO DE CONTRATO  OU  DE  OUTRA  FORMA,  DECORRENTE 
DE, OU EM CONEXÃO COM O SOFTWARE OU O USO OU OUTRAS FUNÇÕES DO SOFTWARE.

Exceto  conforme  contido  no  presente aviso, o nome do(s) dos detentores de direitos autorais acima não 
devem ser utilizados em publicidade ou de outra forma  para  promover  a venda, uso ou outras negociações 
deste Software sem autorização prévia por escrito.

----------------------------                                                                              

EN:                                                                                                       
Permission  is  hereby  granted, free  of  charge,  to  any  person obtaining a copy of this software and 
associated  documentation  files (the "Software"), to deal in the Software without restriction, including 
without  limitation  the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense,  and/or 
sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to 
the following conditions:

The  above  copyright  notice  and  this permission notice shall be included in all copies or substantial 
portions of the Software.

THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,  INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS  FOR  A  PARTICULAR  PURPOSE AND  NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER  LIABILITY,
WHETHER  IN  AN  ACTION  OF  CONTRACT, TORT  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. 

Except  as  contained  in  this  notice,  the name(s) of the above copyright holders shall not be used in
advertising  or  otherwise  to  promote  the  sale,  use or other dealings in this Software without prior
written authorization.

[ Changelog ]

[28/06/2017] - v1 - First Stable Release.

'''

import os, re, sys, json, urllib3, traceback
from lxml import etree

# Receive IP from command-line and validate it
queryIp = sys.argv[1]
if not re.match("^(([1]?[0-9]{1,2}|2([0-4][0-9]|5[0-5]))\.){3}([1]?[0-9]{1,2}|2([0-4][0-9]|5[0-5]))$", queryIp):
    print "Invalid IP Address"
    exit(1)

# Search funcion using geoipfetch.net
def geoIpLookupSite(queryIp):
    geoIpLookupArray = []
    utf8_parser = etree.XMLParser(encoding='utf-8')
    geoIpLookupUrl = 'http://api.geoipfetch.net/?query=' + queryIp
    http = urllib3.PoolManager()
    geoIpRequest = http.request('GET', geoIpLookupUrl, preload_content=False)
    if geoIpRequest.status == 200:
        geoIpXmlFile = geoIpRequest.read()
        geoIpXml = etree.fromstring(geoIpXmlFile, parser=utf8_parser)
        geoIpLookupArray.append(geoIpXml[0][0][0].text)
        geoIpLookupArray.append(geoIpXml[0][0][2].text)
        geoIpLookupArray.append(geoIpXml[0][0][3].text)
        geoIpLookupArray.append(geoIpXml[0][0][5].text)
    return geoIpLookupArray

# Search function using ip-api.com
def ipApiSite(queryIp):
    ipApiArray = []
    ipApiUrl = 'http://ip-api.com/json/' + queryIp
    http = urllib3.PoolManager()
    ipApiRequest = http.request('GET', ipApiUrl, preload_content=False)
    if ipApiRequest.status == 200:
        ipApiJson = json.load(ipApiRequest)
        ipApiArray.append(ipApiJson["query"])
        ipApiArray.append(ipApiJson["isp"])
        ipApiArray.append(ipApiJson["city"])
        ipApiArray.append(ipApiJson["country"])
    return ipApiArray

def main():
    ipInforArray = []
    if len(ipInforArray) == 0:
        ipInforArray = geoIpLookupSite(queryIp)

    if len(ipInforArray) == 0:
        ipInforArray = ipApiSite(queryIp)

    if len(ipInforArray) == 0:
        print "Unable to Check IP Address, try again later"
        exit(1)

    print("IP: %s\nHosted by: %s\nCity: %s\nCountry: %s" % (ipInforArray[0], ipInforArray[1], ipInforArray[2], ipInforArray[3]))
    exit(0)

if __name__ == "__main__":
    try:
        main()
    except IOError:
        print "Forced Exit"
        traceback.print_exc()
